import type { Recipe } from "./types";

/**
 * 이유식·유아반찬 레시피 데이터
 * 단계별로 고르게 분포. 알레르기 태그는 식약처 표시 대상 기준.
 * (일반 가정식 레시피 참고용 — 실제 도입 시 아이 상태·소아과 상담 우선)
 */
export const RECIPES: Recipe[] = [
  // ── 초기 (만 4~6개월) ─────────────────────────────
  {
    id: "rice-puree",
    name: "10배죽 (쌀미음)",
    stage: "초기",
    ageMonths: [4, 6],
    category: "죽/미음",
    summary: "이유식 첫 시작, 가장 묽은 쌀미음.",
    ingredients: [
      { name: "불린 쌀", amount: "10g (약 1큰술)" },
      { name: "물", amount: "100ml" },
    ],
    allergens: [],
    steps: [
      "쌀을 30분 이상 불린 뒤 물기를 뺀다.",
      "불린 쌀과 물을 믹서에 곱게 간다.",
      "약불에서 저어가며 10분간 끓인다.",
      "고운체에 걸러 덩어리 없이 만든다.",
      "체온 정도로 식혀 1~2티스푼부터 먹인다.",
    ],
    timeMinutes: 20,
    servings: "1회분",
    tips: "첫 이유식은 한 가지 재료로 3일간 먹이며 알레르기 반응을 살핀다.",
    tags: ["첫이유식", "기본", "쌀"],
  },
  {
    id: "potato-puree",
    name: "감자미음",
    stage: "초기",
    ageMonths: [5, 6],
    category: "죽/미음",
    summary: "부드럽고 포만감 좋은 감자 미음.",
    ingredients: [
      { name: "감자", amount: "20g" },
      { name: "쌀미음", amount: "100ml" },
    ],
    allergens: [],
    steps: [
      "감자를 껍질 벗겨 작게 썰어 푹 삶는다.",
      "삶은 감자를 으깨 고운체에 내린다.",
      "쌀미음에 감자를 섞어 약불에서 데운다.",
      "농도가 되면 물을 조금 더해 묽게 맞춘다.",
    ],
    timeMinutes: 25,
    servings: "1회분",
    tips: "감자는 단독으로 먼저 테스트한 뒤 쌀과 섞는다.",
    tags: ["감자", "포만감"],
  },
  {
    id: "pumpkin-puree",
    name: "단호박미음",
    stage: "초기",
    ageMonths: [5, 6],
    category: "죽/미음",
    summary: "자연 단맛으로 아기가 잘 먹는 미음.",
    ingredients: [
      { name: "단호박", amount: "20g" },
      { name: "쌀미음", amount: "100ml" },
    ],
    allergens: [],
    steps: [
      "단호박을 쪄서 속을 파내 으깬다.",
      "고운체에 내려 껍질·섬유질을 제거한다.",
      "쌀미음과 섞어 약불에서 데운다.",
    ],
    timeMinutes: 20,
    servings: "1회분",
    tips: "단맛이 강하니 너무 자주 주기보다 채소와 번갈아 준다.",
    tags: ["단호박", "단맛"],
  },

  // ── 중기 (만 7~9개월) ─────────────────────────────
  {
    id: "beef-veggie-porridge",
    name: "소고기 채소죽",
    stage: "중기",
    ageMonths: [7, 9],
    category: "죽/미음",
    summary: "철분 보충에 좋은 대표 중기 이유식.",
    ingredients: [
      { name: "불린 쌀", amount: "20g" },
      { name: "소고기(안심) 다짐", amount: "15g" },
      { name: "애호박", amount: "10g" },
      { name: "당근", amount: "10g" },
      { name: "물", amount: "150ml" },
    ],
    allergens: ["쇠고기"],
    steps: [
      "소고기는 핏물을 빼고 잘게 다진다.",
      "애호박·당근을 곱게 다진다.",
      "냄비에 쌀과 물을 넣고 끓이다 소고기를 넣는다.",
      "채소를 넣고 쌀알이 퍼질 때까지 약불로 끓인다.",
      "입자감 있게 7배죽 정도 농도로 마무리한다.",
    ],
    timeMinutes: 30,
    servings: "1~2회분",
    tips: "소고기 육수를 활용하면 풍미가 좋아진다. 입자는 좁쌀~쌀알 크기.",
    tags: ["철분", "소고기", "인기"],
  },
  {
    id: "chicken-veggie-porridge",
    name: "닭고기 브로콜리죽",
    stage: "중기",
    ageMonths: [8, 9],
    category: "죽/미음",
    summary: "담백한 닭안심과 브로콜리 조합.",
    ingredients: [
      { name: "불린 쌀", amount: "20g" },
      { name: "닭안심 다짐", amount: "15g" },
      { name: "브로콜리(꽃부분)", amount: "10g" },
      { name: "물", amount: "150ml" },
    ],
    allergens: ["닭고기"],
    steps: [
      "닭안심은 힘줄을 제거하고 삶아 잘게 다진다.",
      "브로콜리는 꽃 부분만 데쳐 곱게 다진다.",
      "쌀과 물을 끓이다 닭고기·브로콜리를 넣는다.",
      "약불에서 퍼질 때까지 저어가며 끓인다.",
    ],
    timeMinutes: 30,
    servings: "1~2회분",
    tips: "닭안심은 처음엔 소량으로 알레르기 확인 후 늘린다.",
    tags: ["닭고기", "브로콜리"],
  },
  {
    id: "tofu-veggie-porridge",
    name: "두부 채소죽",
    stage: "중기",
    ageMonths: [7, 9],
    category: "죽/미음",
    summary: "식물성 단백질이 풍부한 부드러운 죽.",
    ingredients: [
      { name: "불린 쌀", amount: "20g" },
      { name: "두부", amount: "20g" },
      { name: "청경채", amount: "10g" },
      { name: "물", amount: "150ml" },
    ],
    allergens: ["대두"],
    steps: [
      "두부는 끓는 물에 데쳐 으깬다.",
      "청경채 잎을 데쳐 곱게 다진다.",
      "쌀과 물을 끓이다 채소를 넣는다.",
      "마지막에 두부를 넣고 한소끔 더 끓인다.",
    ],
    timeMinutes: 25,
    servings: "1~2회분",
    tips: "두부는 오래 끓이면 단단해지니 마지막에 넣는다.",
    tags: ["두부", "단백질"],
  },

  // ── 후기 (만 10~12개월) ───────────────────────────
  {
    id: "soft-rice-egg",
    name: "달걀 진밥",
    stage: "후기",
    ageMonths: [10, 12],
    category: "밥/진밥",
    summary: "부드러운 달걀을 푼 영양 진밥.",
    ingredients: [
      { name: "진밥", amount: "60g" },
      { name: "달걀", amount: "1/2개" },
      { name: "시금치", amount: "10g" },
      { name: "물", amount: "100ml" },
    ],
    allergens: ["계란"],
    steps: [
      "시금치를 데쳐 잘게 썬다.",
      "냄비에 진밥과 물을 넣고 끓인다.",
      "시금치를 넣고 풀어둔 달걀을 둘러 넣는다.",
      "달걀이 익을 때까지 부드럽게 저어준다.",
    ],
    timeMinutes: 15,
    servings: "1회분",
    tips: "달걀은 완전히 익혀서 준다. 노른자 먼저 시도 후 흰자.",
    tags: ["달걀", "철분"],
  },
  {
    id: "fish-radish-soup",
    name: "대구 무국",
    stage: "후기",
    ageMonths: [11, 12],
    category: "국/찌개",
    summary: "흰살생선과 무로 끓인 시원한 국.",
    ingredients: [
      { name: "대구살", amount: "20g" },
      { name: "무", amount: "20g" },
      { name: "다시마 육수", amount: "150ml" },
    ],
    allergens: ["생선"],
    steps: [
      "대구살은 가시를 꼼꼼히 발라 한입 크기로 썬다.",
      "무는 얇게 채 썰어 육수에 넣고 끓인다.",
      "무가 투명해지면 대구살을 넣는다.",
      "생선이 익을 때까지 끓이고 간은 하지 않는다.",
    ],
    timeMinutes: 20,
    servings: "1회분",
    tips: "생선 가시는 반드시 두 번 확인. 흰살생선부터 시작한다.",
    tags: ["생선", "무"],
  },
  {
    id: "veggie-jeon",
    name: "애호박 달걀전",
    stage: "후기",
    ageMonths: [10, 12],
    category: "핑거푸드",
    summary: "손으로 집어 먹기 좋은 부드러운 전.",
    ingredients: [
      { name: "애호박", amount: "30g" },
      { name: "달걀", amount: "1개" },
      { name: "쌀가루", amount: "1큰술" },
    ],
    allergens: ["계란"],
    steps: [
      "애호박을 곱게 채 썰거나 다진다.",
      "달걀, 쌀가루, 애호박을 섞는다.",
      "약불 팬에 기름을 살짝 두르고 작게 부친다.",
      "스틱 모양으로 잘라 식혀 준다.",
    ],
    timeMinutes: 15,
    servings: "2회분",
    tips: "기름은 키친타월로 닦아내듯 최소화한다.",
    tags: ["핑거푸드", "자기주도", "달걀"],
  },

  // ── 완료기 (만 12~15개월) ─────────────────────────
  {
    id: "soy-beef-bites",
    name: "소고기 무조림",
    stage: "완료기",
    ageMonths: [12, 15],
    category: "반찬",
    summary: "간을 약하게 한 첫 조림 반찬.",
    ingredients: [
      { name: "소고기(불고기감)", amount: "30g" },
      { name: "무", amount: "30g" },
      { name: "간장", amount: "1/2티스푼" },
      { name: "배즙", amount: "1큰술" },
      { name: "물", amount: "100ml" },
    ],
    allergens: ["쇠고기", "대두"],
    steps: [
      "소고기와 무를 한입보다 작게 썬다.",
      "물, 간장, 배즙을 넣고 약불에서 끓인다.",
      "무가 익고 국물이 자작해질 때까지 졸인다.",
    ],
    timeMinutes: 25,
    servings: "2회분",
    tips: "간장은 아주 소량. 배즙으로 단맛과 연육 효과를 낸다.",
    tags: ["반찬", "소고기", "조림"],
  },
  {
    id: "egg-tofu-steam",
    name: "두부 달걀찜",
    stage: "완료기",
    ageMonths: [12, 15],
    category: "반찬",
    summary: "촉촉하게 쪄낸 단백질 듬뿍 반찬.",
    ingredients: [
      { name: "달걀", amount: "1개" },
      { name: "두부", amount: "30g" },
      { name: "당근", amount: "5g" },
      { name: "물 또는 육수", amount: "50ml" },
    ],
    allergens: ["계란", "대두"],
    steps: [
      "두부를 으깨고 당근을 곱게 다진다.",
      "달걀을 풀어 두부·당근·물을 섞는다.",
      "내열 용기에 담아 김 오른 찜기에 10분 찐다.",
      "젓가락으로 찔러 묻어나지 않으면 완성.",
    ],
    timeMinutes: 20,
    servings: "2회분",
    tips: "전자레인지로도 가능(2분 내외, 중간에 한 번 저어줌).",
    tags: ["달걀", "두부", "찜"],
  },

  // ── 유아식 (만 15개월+) ───────────────────────────
  {
    id: "kid-bibimbap",
    name: "아기 비빔밥",
    stage: "유아식",
    ageMonths: [15, 36],
    category: "밥/진밥",
    summary: "여러 채소를 한 그릇에 담은 영양밥.",
    ingredients: [
      { name: "진밥/밥", amount: "80g" },
      { name: "소고기 다짐", amount: "20g" },
      { name: "애호박·당근·시금치", amount: "각 10g" },
      { name: "참기름", amount: "약간" },
    ],
    allergens: ["쇠고기"],
    steps: [
      "채소를 각각 다져 살짝 볶는다.",
      "소고기는 간 없이 볶는다.",
      "밥 위에 재료를 올리고 참기름 한 방울 두른다.",
      "잘 섞어 먹기 좋은 농도로 만든다.",
    ],
    timeMinutes: 20,
    servings: "1~2회분",
    tips: "아이가 직접 섞게 하면 식사 흥미를 높일 수 있다.",
    tags: ["비빔밥", "채소", "자기주도"],
  },
  {
    id: "cheese-potato-ball",
    name: "감자 치즈볼",
    stage: "유아식",
    ageMonths: [15, 36],
    category: "간식",
    summary: "쫀득한 감자에 치즈를 넣은 손가락 간식.",
    ingredients: [
      { name: "감자", amount: "100g" },
      { name: "아기치즈", amount: "1/2장" },
      { name: "분유 또는 우유", amount: "1큰술" },
    ],
    allergens: ["우유"],
    steps: [
      "감자를 삶아 뜨거울 때 곱게 으깬다.",
      "우유를 조금 넣어 반죽 농도를 맞춘다.",
      "한입 크기로 떼어 치즈를 넣고 동그랗게 빚는다.",
      "에어프라이어 160도에서 8분 굽거나 팬에 굴린다.",
    ],
    timeMinutes: 25,
    servings: "8~10개",
    tips: "치즈는 나트륨이 있으니 아기 전용 저염 치즈를 쓴다.",
    tags: ["간식", "치즈", "핑거푸드"],
  },
  {
    id: "banana-pancake",
    name: "바나나 오트팬케이크",
    stage: "유아식",
    ageMonths: [15, 36],
    category: "간식",
    summary: "설탕 없이 바나나 단맛만으로 만든 간식.",
    ingredients: [
      { name: "바나나", amount: "1개" },
      { name: "달걀", amount: "1개" },
      { name: "오트밀(곱게 간 것)", amount: "2큰술" },
    ],
    allergens: ["계란", "밀"],
    steps: [
      "바나나를 포크로 곱게 으깬다.",
      "달걀과 오트밀을 넣어 반죽한다.",
      "약불 팬에 한 숟갈씩 올려 양면을 부친다.",
      "한입 크기로 잘라 식혀 준다.",
    ],
    timeMinutes: 15,
    servings: "2회분",
    tips: "오트밀이 밀과 교차오염될 수 있으니 글루텐 민감 시 주의.",
    tags: ["간식", "바나나", "노설탕"],
  },
];

/** id로 레시피 찾기 */
export function getRecipe(id: string): Recipe | undefined {
  return RECIPES.find((r) => r.id === id);
}
