import type { Recipe } from "./types";

/**
 * 이유식·유아반찬 레시피 데이터
 * 단계별로 고르게 분포. 알레르기 태그는 식약처 표시 대상 기준.
 * (일반 가정식 레시피 참고용 — 실제 도입 시 아이 상태·소아과 상담 우선)
 */
export const RECIPES: Recipe[] = [
  // ── 초기 (만 4~6개월) ─────────────────────────────
  {
    id: "rice-puree",
    name: "10배죽 (쌀미음)",
    stage: "초기",
    ageMonths: [4, 6],
    category: "죽/미음",
    summary: "이유식 첫 시작, 가장 묽은 쌀미음.",
    ingredients: [
      { name: "불린 쌀", amount: "10g (약 1큰술)" },
      { name: "물", amount: "100ml" },
    ],
    allergens: [],
    steps: [
      "쌀을 30분 이상 불린 뒤 물기를 뺀다.",
      "불린 쌀과 물을 믹서에 곱게 간다.",
      "약불에서 저어가며 10분간 끓인다.",
      "고운체에 걸러 덩어리 없이 만든다.",
      "체온 정도로 식혀 1~2티스푼부터 먹인다.",
    ],
    timeMinutes: 20,
    servings: "1회분",
    tips: "첫 이유식은 한 가지 재료로 3일간 먹이며 알레르기 반응을 살핀다.",
    tags: ["첫이유식", "기본", "쌀"],
  },
  {
    id: "potato-puree",
    name: "감자미음",
    stage: "초기",
    ageMonths: [5, 6],
    category: "죽/미음",
    summary: "부드럽고 포만감 좋은 감자 미음.",
    ingredients: [
      { name: "감자", amount: "20g" },
      { name: "쌀미음", amount: "100ml" },
    ],
    allergens: [],
    steps: [
      "감자를 껍질 벗겨 작게 썰어 푹 삶는다.",
      "삶은 감자를 으깨 고운체에 내린다.",
      "쌀미음에 감자를 섞어 약불에서 데운다.",
      "농도가 되면 물을 조금 더해 묽게 맞춘다.",
    ],
    timeMinutes: 25,
    servings: "1회분",
    tips: "감자는 단독으로 먼저 테스트한 뒤 쌀과 섞는다.",
    tags: ["감자", "포만감"],
  },
  {
    id: "pumpkin-puree",
    name: "단호박미음",
    stage: "초기",
    ageMonths: [5, 6],
    category: "죽/미음",
    summary: "자연 단맛으로 아기가 잘 먹는 미음.",
    ingredients: [
      { name: "단호박", amount: "20g" },
      { name: "쌀미음", amount: "100ml" },
    ],
    allergens: [],
    steps: [
      "단호박을 쪄서 속을 파내 으깬다.",
      "고운체에 내려 껍질·섬유질을 제거한다.",
      "쌀미음과 섞어 약불에서 데운다.",
    ],
    timeMinutes: 20,
    servings: "1회분",
    tips: "단맛이 강하니 너무 자주 주기보다 채소와 번갈아 준다.",
    tags: ["단호박", "단맛"],
  },

  // ── 중기 (만 7~9개월) ─────────────────────────────
  {
    id: "beef-veggie-porridge",
    name: "소고기 채소죽",
    stage: "중기",
    ageMonths: [7, 9],
    category: "죽/미음",
    summary: "철분 보충에 좋은 대표 중기 이유식.",
    ingredients: [
      { name: "불린 쌀", amount: "20g" },
      { name: "소고기(안심) 다짐", amount: "15g" },
      { name: "애호박", amount: "10g" },
      { name: "당근", amount: "10g" },
      { name: "물", amount: "150ml" },
    ],
    allergens: ["쇠고기"],
    steps: [
      "소고기는 핏물을 빼고 잘게 다진다.",
      "애호박·당근을 곱게 다진다.",
      "냄비에 쌀과 물을 넣고 끓이다 소고기를 넣는다.",
      "채소를 넣고 쌀알이 퍼질 때까지 약불로 끓인다.",
      "입자감 있게 7배죽 정도 농도로 마무리한다.",
    ],
    timeMinutes: 30,
    servings: "1~2회분",
    tips: "소고기 육수를 활용하면 풍미가 좋아진다. 입자는 좁쌀~쌀알 크기.",
    tags: ["철분", "소고기", "인기"],
  },
  {
    id: "chicken-veggie-porridge",
    name: "닭고기 브로콜리죽",
    stage: "중기",
    ageMonths: [8, 9],
    category: "죽/미음",
    summary: "담백한 닭안심과 브로콜리 조합.",
    ingredients: [
      { name: "불린 쌀", amount: "20g" },
      { name: "닭안심 다짐", amount: "15g" },
      { name: "브로콜리(꽃부분)", amount: "10g" },
      { name: "물", amount: "150ml" },
    ],
    allergens: ["닭고기"],
    steps: [
      "닭안심은 힘줄을 제거하고 삶아 잘게 다진다.",
      "브로콜리는 꽃 부분만 데쳐 곱게 다진다.",
      "쌀과 물을 끓이다 닭고기·브로콜리를 넣는다.",
      "약불에서 퍼질 때까지 저어가며 끓인다.",
    ],
    timeMinutes: 30,
    servings: "1~2회분",
    tips: "닭안심은 처음엔 소량으로 알레르기 확인 후 늘린다.",
    tags: ["닭고기", "브로콜리"],
  },
  {
    id: "tofu-veggie-porridge",
    name: "두부 채소죽",
    stage: "중기",
    ageMonths: [7, 9],
    category: "죽/미음",
    summary: "식물성 단백질이 풍부한 부드러운 죽.",
    ingredients: [
      { name: "불린 쌀", amount: "20g" },
      { name: "두부", amount: "20g" },
      { name: "청경채", amount: "10g" },
      { name: "물", amount: "150ml" },
    ],
    allergens: ["대두"],
    steps: [
      "두부는 끓는 물에 데쳐 으깬다.",
      "청경채 잎을 데쳐 곱게 다진다.",
      "쌀과 물을 끓이다 채소를 넣는다.",
      "마지막에 두부를 넣고 한소끔 더 끓인다.",
    ],
    timeMinutes: 25,
    servings: "1~2회분",
    tips: "두부는 오래 끓이면 단단해지니 마지막에 넣는다.",
    tags: ["두부", "단백질"],
  },

  // ── 후기 (만 10~12개월) ───────────────────────────
  {
    id: "soft-rice-egg",
    name: "달걀 진밥",
    stage: "후기",
    ageMonths: [10, 12],
    category: "밥/진밥",
    summary: "부드러운 달걀을 푼 영양 진밥.",
    ingredients: [
      { name: "진밥", amount: "60g" },
      { name: "달걀", amount: "1/2개" },
      { name: "시금치", amount: "10g" },
      { name: "물", amount: "100ml" },
    ],
    allergens: ["계란"],
    steps: [
      "시금치를 데쳐 잘게 썬다.",
      "냄비에 진밥과 물을 넣고 끓인다.",
      "시금치를 넣고 풀어둔 달걀을 둘러 넣는다.",
      "달걀이 익을 때까지 부드럽게 저어준다.",
    ],
    timeMinutes: 15,
    servings: "1회분",
    tips: "달걀은 완전히 익혀서 준다. 노른자 먼저 시도 후 흰자.",
    tags: ["달걀", "철분"],
  },
  {
    id: "fish-radish-soup",
    name: "대구 무국",
    stage: "후기",
    ageMonths: [11, 12],
    category: "국/찌개",
    summary: "흰살생선과 무로 끓인 시원한 국.",
    ingredients: [
      { name: "대구살", amount: "20g" },
      { name: "무", amount: "20g" },
      { name: "다시마 육수", amount: "150ml" },
    ],
    allergens: ["생선"],
    steps: [
      "대구살은 가시를 꼼꼼히 발라 한입 크기로 썬다.",
      "무는 얇게 채 썰어 육수에 넣고 끓인다.",
      "무가 투명해지면 대구살을 넣는다.",
      "생선이 익을 때까지 끓이고 간은 하지 않는다.",
    ],
    timeMinutes: 20,
    servings: "1회분",
    tips: "생선 가시는 반드시 두 번 확인. 흰살생선부터 시작한다.",
    tags: ["생선", "무"],
  },
  {
    id: "veggie-jeon",
    name: "애호박 달걀전",
    stage: "후기",
    ageMonths: [10, 12],
    category: "핑거푸드",
    summary: "손으로 집어 먹기 좋은 부드러운 전.",
    ingredients: [
      { name: "애호박", amount: "30g" },
      { name: "달걀", amount: "1개" },
      { name: "쌀가루", amount: "1큰술" },
    ],
    allergens: ["계란"],
    steps: [
      "애호박을 곱게 채 썰거나 다진다.",
      "달걀, 쌀가루, 애호박을 섞는다.",
      "약불 팬에 기름을 살짝 두르고 작게 부친다.",
      "스틱 모양으로 잘라 식혀 준다.",
    ],
    timeMinutes: 15,
    servings: "2회분",
    tips: "기름은 키친타월로 닦아내듯 최소화한다.",
    tags: ["핑거푸드", "자기주도", "달걀"],
  },

  // ── 완료기 (만 12~15개월) ─────────────────────────
  {
    id: "soy-beef-bites",
    name: "소고기 무조림",
    stage: "완료기",
    ageMonths: [12, 15],
    category: "반찬",
    summary: "간을 약하게 한 첫 조림 반찬.",
    ingredients: [
      { name: "소고기(불고기감)", amount: "30g" },
      { name: "무", amount: "30g" },
      { name: "간장", amount: "1/2티스푼" },
      { name: "배즙", amount: "1큰술" },
      { name: "물", amount: "100ml" },
    ],
    allergens: ["쇠고기", "대두"],
    steps: [
      "소고기와 무를 한입보다 작게 썬다.",
      "물, 간장, 배즙을 넣고 약불에서 끓인다.",
      "무가 익고 국물이 자작해질 때까지 졸인다.",
    ],
    timeMinutes: 25,
    servings: "2회분",
    tips: "간장은 아주 소량. 배즙으로 단맛과 연육 효과를 낸다.",
    tags: ["반찬", "소고기", "조림"],
  },
  {
    id: "egg-tofu-steam",
    name: "두부 달걀찜",
    stage: "완료기",
    ageMonths: [12, 15],
    category: "반찬",
    summary: "촉촉하게 쪄낸 단백질 듬뿍 반찬.",
    ingredients: [
      { name: "달걀", amount: "1개" },
      { name: "두부", amount: "30g" },
      { name: "당근", amount: "5g" },
      { name: "물 또는 육수", amount: "50ml" },
    ],
    allergens: ["계란", "대두"],
    steps: [
      "두부를 으깨고 당근을 곱게 다진다.",
      "달걀을 풀어 두부·당근·물을 섞는다.",
      "내열 용기에 담아 김 오른 찜기에 10분 찐다.",
      "젓가락으로 찔러 묻어나지 않으면 완성.",
    ],
    timeMinutes: 20,
    servings: "2회분",
    tips: "전자레인지로도 가능(2분 내외, 중간에 한 번 저어줌).",
    tags: ["달걀", "두부", "찜"],
  },

  // ── 유아식: 구간별 (유아 1세 / 2~3세 / 4~5세) ──────
  {
    id: "kid-bibimbap",
    name: "아기 비빔밥",
    stage: "유아 2~3세",
    ageMonths: [24, 48],
    category: "밥/진밥",
    summary: "여러 채소를 한 그릇에 담은 영양밥.",
    ingredients: [
      { name: "진밥/밥", amount: "80g" },
      { name: "소고기 다짐", amount: "20g" },
      { name: "애호박·당근·시금치", amount: "각 10g" },
      { name: "참기름", amount: "약간" },
    ],
    allergens: ["쇠고기"],
    steps: [
      "채소를 각각 다져 살짝 볶는다.",
      "소고기는 간 없이 볶는다.",
      "밥 위에 재료를 올리고 참기름 한 방울 두른다.",
      "잘 섞어 먹기 좋은 농도로 만든다.",
    ],
    timeMinutes: 20,
    servings: "1~2회분",
    tips: "아이가 직접 섞게 하면 식사 흥미를 높일 수 있다.",
    tags: ["비빔밥", "채소", "자기주도"],
  },
  {
    id: "cheese-potato-ball",
    name: "감자 치즈볼",
    stage: "유아 1세",
    ageMonths: [12, 24],
    category: "간식",
    summary: "쫀득한 감자에 치즈를 넣은 손가락 간식.",
    ingredients: [
      { name: "감자", amount: "100g" },
      { name: "아기치즈", amount: "1/2장" },
      { name: "분유 또는 우유", amount: "1큰술" },
    ],
    allergens: ["우유"],
    steps: [
      "감자를 삶아 뜨거울 때 곱게 으깬다.",
      "우유를 조금 넣어 반죽 농도를 맞춘다.",
      "한입 크기로 떼어 치즈를 넣고 동그랗게 빚는다.",
      "에어프라이어 160도에서 8분 굽거나 팬에 굴린다.",
    ],
    timeMinutes: 25,
    servings: "8~10개",
    tips: "치즈는 나트륨이 있으니 아기 전용 저염 치즈를 쓴다.",
    tags: ["간식", "치즈", "핑거푸드"],
  },
  {
    id: "banana-pancake",
    name: "바나나 오트팬케이크",
    stage: "유아 1세",
    ageMonths: [12, 24],
    category: "간식",
    summary: "설탕 없이 바나나 단맛만으로 만든 간식.",
    ingredients: [
      { name: "바나나", amount: "1개" },
      { name: "달걀", amount: "1개" },
      { name: "오트밀(곱게 간 것)", amount: "2큰술" },
    ],
    allergens: ["계란", "밀"],
    steps: [
      "바나나를 포크로 곱게 으깬다.",
      "달걀과 오트밀을 넣어 반죽한다.",
      "약불 팬에 한 숟갈씩 올려 양면을 부친다.",
      "한입 크기로 잘라 식혀 준다.",
    ],
    timeMinutes: 15,
    servings: "2회분",
    tips: "오트밀이 밀과 교차오염될 수 있으니 글루텐 민감 시 주의.",
    tags: ["간식", "바나나", "노설탕"],
  },

  // ── 유아 1세 (만 12~24개월) ──
  {
    id: "chicken-veg-rice",
    name: "닭고기 채소 진밥",
    stage: "유아 1세",
    ageMonths: [12, 24],
    category: "밥/진밥",
    summary: "닭안심과 채소를 부드럽게 익힌 한 그릇 진밥.",
    ingredients: [
      { name: "진밥", amount: "80g" },
      { name: "닭안심", amount: "20g" },
      { name: "애호박·당근", amount: "각 10g" },
      { name: "닭육수 또는 물", amount: "60ml" },
    ],
    allergens: ["닭고기"],
    steps: [
      "닭안심을 삶아 잘게 찢거나 다진다.",
      "애호박·당근을 곱게 다진다.",
      "냄비에 진밥·채소·닭고기·육수를 넣는다.",
      "약불에서 저어가며 채소가 무를 때까지 끓인다.",
    ],
    timeMinutes: 20,
    servings: "1회분",
    tips: "간은 하지 않고 닭육수의 감칠맛으로 충분합니다.",
    tags: ["닭고기", "진밥", "한그릇"],
  },
  {
    id: "tofu-egg-jeon",
    name: "두부 달걀 미니전",
    stage: "유아 1세",
    ageMonths: [12, 24],
    category: "반찬",
    summary: "두부와 달걀을 섞어 한입 크기로 부친 손가락 반찬.",
    ingredients: [
      { name: "두부", amount: "50g" },
      { name: "달걀", amount: "1개" },
      { name: "당근·애호박", amount: "각 10g" },
    ],
    allergens: ["대두", "계란"],
    steps: [
      "두부는 물기를 꼭 짜 으깬다.",
      "당근·애호박을 곱게 다진다.",
      "두부·달걀·채소를 고루 섞는다.",
      "약불 팬에 한 숟갈씩 올려 한입 크기로 노릇하게 부친다.",
    ],
    timeMinutes: 15,
    servings: "2회분",
    tips: "기름은 키친타월로 얇게 펴 바르면 느끼하지 않아요.",
    tags: ["두부", "달걀", "핑거푸드"],
  },

  // ── 유아 2~3세 (만 24~48개월) ──
  {
    id: "veggie-anchovy-riceball",
    name: "채소 주먹밥",
    stage: "유아 2~3세",
    ageMonths: [24, 48],
    category: "밥/진밥",
    summary: "아이가 손으로 집어 먹기 좋은 한입 주먹밥.",
    ingredients: [
      { name: "밥", amount: "100g" },
      { name: "당근·애호박·시금치", amount: "각 10g" },
      { name: "참기름·통깨", amount: "약간" },
      { name: "구운 김가루", amount: "약간" },
    ],
    allergens: [],
    steps: [
      "채소를 잘게 다져 기름 없이 살짝 볶는다.",
      "밥에 채소·김가루·참기름을 넣어 섞는다.",
      "한입 크기로 동그랗게 뭉친다.",
      "통깨를 살짝 묻혀 마무리한다.",
    ],
    timeMinutes: 15,
    servings: "6~8개",
    tips: "스스로 집어 먹게 두면 자기주도 식사 연습이 됩니다.",
    tags: ["주먹밥", "자기주도", "채소"],
  },
  {
    id: "tofu-beef-meatball",
    name: "두부 소고기 완자조림",
    stage: "유아 2~3세",
    ageMonths: [24, 48],
    category: "반찬",
    summary: "두부로 부드럽게 만든 완자를 약한 간으로 조린 반찬.",
    ingredients: [
      { name: "두부", amount: "60g" },
      { name: "소고기 다짐", amount: "40g" },
      { name: "양파", amount: "10g" },
      { name: "간장·물", amount: "각 약간" },
    ],
    allergens: ["대두", "쇠고기", "밀"],
    steps: [
      "두부는 물기를 짜고, 양파는 곱게 다진다.",
      "두부·소고기·양파를 섞어 한입 완자로 빚는다.",
      "팬에 굴려가며 겉을 익힌다.",
      "물과 간장을 아주 약간 넣어 조려 윤기를 낸다.",
    ],
    timeMinutes: 25,
    servings: "2~3회분",
    tips: "간장은 1/4작은술 이하로, 어른 입에 심심할 정도가 적당합니다.",
    tags: ["두부", "소고기", "완자"],
  },
  {
    id: "mild-doenjang-soup",
    name: "순한 채소 된장국",
    stage: "유아 2~3세",
    ageMonths: [24, 48],
    category: "국/찌개",
    summary: "된장을 아주 연하게 푼 순한 채소국.",
    ingredients: [
      { name: "두부", amount: "40g" },
      { name: "애호박·감자", amount: "각 20g" },
      { name: "된장", amount: "1/2작은술" },
      { name: "다시물", amount: "200ml" },
    ],
    allergens: ["대두"],
    steps: [
      "감자·애호박을 작게 깍둑썬다.",
      "다시물에 감자를 넣어 먼저 익힌다.",
      "된장을 아주 연하게 풀고 애호박·두부를 넣는다.",
      "채소가 무를 때까지 끓인다.",
    ],
    timeMinutes: 20,
    servings: "2회분",
    tips: "된장은 나트륨이 높아 어른 국의 1/3 농도로 연하게 푸세요.",
    tags: ["된장국", "채소", "순한맛"],
  },

  // ── 유아 4~5세 (만 48~72개월) ──
  {
    id: "beef-fried-rice",
    name: "소고기 채소 볶음밥",
    stage: "유아 4~5세",
    ageMonths: [48, 72],
    category: "밥/진밥",
    summary: "다진 채소를 듬뿍 넣은 균형 잡힌 볶음밥.",
    ingredients: [
      { name: "밥", amount: "120g" },
      { name: "소고기 다짐", amount: "40g" },
      { name: "당근·애호박·양파", amount: "각 15g" },
      { name: "간장", amount: "1/2작은술" },
    ],
    allergens: ["쇠고기", "대두", "밀"],
    steps: [
      "채소를 잘게 다진다.",
      "소고기를 먼저 볶다가 채소를 넣어 익힌다.",
      "밥을 넣고 간장을 약간 둘러 고슬하게 볶는다.",
      "한 김 식혀 먹기 좋게 담는다.",
    ],
    timeMinutes: 20,
    servings: "1~2회분",
    tips: "달걀 지단을 부쳐 올리면 단백질과 색감을 더할 수 있어요.",
    tags: ["볶음밥", "소고기", "한그릇"],
  },
  {
    id: "mild-curry-rice",
    name: "순한 카레라이스",
    stage: "유아 4~5세",
    ageMonths: [48, 72],
    category: "밥/진밥",
    summary: "유아용 순한 카레로 만든 든든한 한 끼.",
    ingredients: [
      { name: "밥", amount: "120g" },
      { name: "닭안심 또는 소고기", amount: "40g" },
      { name: "감자·당근·양파", amount: "각 20g" },
      { name: "유아용 순한 카레", amount: "1조각" },
    ],
    allergens: ["밀", "닭고기"],
    steps: [
      "고기와 채소를 한입 크기로 썬다.",
      "냄비에 고기를 볶다가 채소를 넣어 익힌다.",
      "물을 붓고 감자가 익을 때까지 끓인다.",
      "불을 줄여 카레를 풀고 걸쭉해질 때까지 저어준다.",
    ],
    timeMinutes: 25,
    servings: "2회분",
    tips: "시판 카레는 나트륨이 높으니 유아 전용 순한맛을 쓰고 물을 넉넉히 잡으세요.",
    tags: ["카레", "한그릇", "채소"],
  },
  {
    id: "tofu-steak",
    name: "두부 스테이크",
    stage: "유아 4~5세",
    ageMonths: [48, 72],
    category: "반찬",
    summary: "두부와 채소를 뭉쳐 노릇하게 구운 든든한 반찬.",
    ingredients: [
      { name: "두부", amount: "100g" },
      { name: "달걀", amount: "1/2개" },
      { name: "빵가루", amount: "2큰술" },
      { name: "당근·양파", amount: "각 15g" },
    ],
    allergens: ["대두", "계란", "밀"],
    steps: [
      "두부는 물기를 꼭 짜 으깬다.",
      "다진 채소·달걀·빵가루를 섞어 반죽한다.",
      "납작한 스테이크 모양으로 빚는다.",
      "약불 팬에 양면을 노릇하게 구워준다.",
    ],
    timeMinutes: 20,
    servings: "2회분",
    tips: "케첩 대신 으깬 토마토를 살짝 곁들이면 더 좋아요.",
    tags: ["두부", "스테이크", "단백질"],
  },
  {
    id: "beef-seaweed-soup",
    name: "소고기 미역국",
    stage: "유아 4~5세",
    ageMonths: [48, 72],
    category: "국/찌개",
    summary: "철분과 칼슘이 풍부한 부드러운 미역국.",
    ingredients: [
      { name: "불린 미역", amount: "30g" },
      { name: "소고기 다짐", amount: "30g" },
      { name: "국간장", amount: "1/2작은술" },
      { name: "물", amount: "300ml" },
    ],
    allergens: ["쇠고기", "대두", "밀"],
    steps: [
      "불린 미역을 먹기 좋게 자른다.",
      "소고기를 냄비에 볶다가 미역을 넣어 함께 볶는다.",
      "물을 붓고 중약불로 15분 이상 끓인다.",
      "국간장으로 아주 약하게 간한다.",
    ],
    timeMinutes: 25,
    servings: "2~3회분",
    tips: "오래 끓일수록 미역이 부드러워져 아이가 먹기 좋아요.",
    tags: ["미역국", "소고기", "철분"],
  },

  // ── 콘텐츠 확장 (2026-06-10, +20종) ──
  // 초기 (만 4~6개월)
  {
    id: "broccoli-puree",
    name: "브로콜리미음",
    stage: "초기",
    ageMonths: [5, 6],
    category: "죽/미음",
    summary: "초록 채소를 부드럽게 익혀 만든 미음.",
    ingredients: [
      { name: "브로콜리 꽃 부분", amount: "15g" },
      { name: "쌀미음", amount: "100ml" },
    ],
    allergens: [],
    steps: [
      "브로콜리 꽃 부분만 데쳐 곱게 간다.",
      "고운체에 내려 줄기·덩어리를 거른다.",
      "쌀미음에 섞어 약불에서 데운다.",
    ],
    timeMinutes: 20,
    servings: "1회분",
    tips: "줄기보다 부드러운 꽃 부분부터 시작해요.",
    tags: ["브로콜리", "채소", "기본"],
  },
  {
    id: "cabbage-puree",
    name: "양배추미음",
    stage: "초기",
    ageMonths: [5, 6],
    category: "죽/미음",
    summary: "단맛이 은은한 양배추를 곱게 간 미음.",
    ingredients: [
      { name: "양배추 잎", amount: "15g" },
      { name: "쌀미음", amount: "100ml" },
    ],
    allergens: [],
    steps: [
      "양배추 잎의 두꺼운 심을 제거하고 푹 찐다.",
      "곱게 갈아 고운체에 내린다.",
      "쌀미음에 섞어 약불에서 데운다.",
    ],
    timeMinutes: 20,
    servings: "1회분",
    tips: "익히면 단맛이 올라와 아기가 잘 먹어요.",
    tags: ["양배추", "채소"],
  },
  {
    id: "sweet-potato-puree",
    name: "고구마미음",
    stage: "초기",
    ageMonths: [5, 6],
    category: "죽/미음",
    summary: "자연 단맛이 좋은 고구마 미음.",
    ingredients: [
      { name: "고구마", amount: "20g" },
      { name: "쌀미음", amount: "100ml" },
    ],
    allergens: [],
    steps: [
      "고구마를 쪄서 곱게 으깬다.",
      "고운체에 내려 섬유질을 거른다.",
      "쌀미음에 섞어 농도를 묽게 맞춘다.",
    ],
    timeMinutes: 25,
    servings: "1회분",
    tips: "변비가 있으면 수분을 넉넉히 잡아주세요.",
    tags: ["고구마", "단맛"],
  },
  {
    id: "apple-puree",
    name: "사과퓨레",
    stage: "초기",
    ageMonths: [5, 6],
    category: "간식",
    summary: "익혀서 부드럽게 만든 첫 과일 퓨레.",
    ingredients: [
      { name: "사과", amount: "30g" },
      { name: "물", amount: "약간" },
    ],
    allergens: [],
    steps: [
      "사과를 껍질 벗겨 작게 썬다.",
      "물을 약간 넣고 푹 익힌다.",
      "곱게 갈아 고운체에 내린다.",
    ],
    timeMinutes: 15,
    servings: "1회분",
    tips: "처음엔 익혀서, 익숙해지면 생과일로 진행해요.",
    tags: ["사과", "과일", "간식"],
  },

  // 중기 (만 7~9개월)
  {
    id: "chicken-carrot-porridge",
    name: "닭고기 당근죽",
    stage: "중기",
    ageMonths: [7, 9],
    category: "죽/미음",
    summary: "담백한 닭안심과 당근을 넣은 죽.",
    ingredients: [
      { name: "불린 쌀", amount: "15g" },
      { name: "닭안심", amount: "15g" },
      { name: "당근", amount: "10g" },
      { name: "물", amount: "150ml" },
    ],
    allergens: ["닭고기"],
    steps: [
      "닭안심을 삶아 곱게 다진다.",
      "당근은 푹 익혀 잘게 다진다.",
      "쌀과 물을 넣고 끓이다가 재료를 넣어 죽으로 끓인다.",
    ],
    timeMinutes: 25,
    servings: "1~2회분",
    tips: "닭육수로 끓이면 감칠맛이 좋아져요.",
    tags: ["닭고기", "당근", "죽"],
  },
  {
    id: "cod-veggie-porridge",
    name: "대구 채소죽",
    stage: "중기",
    ageMonths: [8, 9],
    category: "죽/미음",
    summary: "흰살생선과 채소로 끓인 부드러운 죽.",
    ingredients: [
      { name: "불린 쌀", amount: "15g" },
      { name: "대구살", amount: "15g" },
      { name: "애호박", amount: "10g" },
      { name: "물", amount: "150ml" },
    ],
    allergens: ["생선"],
    steps: [
      "대구살의 가시를 꼼꼼히 제거하고 익혀 으깬다.",
      "애호박은 곱게 다진다.",
      "쌀과 물을 끓이다가 재료를 넣어 죽으로 끓인다.",
    ],
    timeMinutes: 25,
    servings: "1~2회분",
    tips: "가시 제거를 가장 꼼꼼히, 완전히 익혀 주세요.",
    tags: ["대구", "생선", "죽"],
  },
  {
    id: "sweet-potato-chicken-porridge",
    name: "고구마 닭죽",
    stage: "중기",
    ageMonths: [7, 9],
    category: "죽/미음",
    summary: "고구마의 단맛과 닭고기 단백질을 함께.",
    ingredients: [
      { name: "불린 쌀", amount: "15g" },
      { name: "닭안심", amount: "15g" },
      { name: "고구마", amount: "15g" },
      { name: "물", amount: "150ml" },
    ],
    allergens: ["닭고기"],
    steps: [
      "닭안심을 삶아 곱게 다진다.",
      "고구마는 쪄서 으깬다.",
      "쌀과 물을 끓이다가 재료를 넣어 죽으로 끓인다.",
    ],
    timeMinutes: 25,
    servings: "1~2회분",
    tips: "고구마가 들어가 농도가 빨리 되니 물을 넉넉히.",
    tags: ["고구마", "닭고기", "죽"],
  },

  // 후기 (만 10~12개월)
  {
    id: "beef-mushroom-rice",
    name: "소고기 버섯 진밥",
    stage: "후기",
    ageMonths: [10, 12],
    category: "밥/진밥",
    summary: "감칠맛 좋은 버섯과 소고기를 넣은 진밥.",
    ingredients: [
      { name: "진밥", amount: "70g" },
      { name: "소고기 다짐", amount: "20g" },
      { name: "표고버섯", amount: "10g" },
      { name: "물", amount: "60ml" },
    ],
    allergens: ["쇠고기"],
    steps: [
      "버섯은 기둥을 떼고 곱게 다진다.",
      "소고기를 볶다가 버섯을 넣어 익힌다.",
      "진밥과 물을 넣어 부드럽게 끓인다.",
    ],
    timeMinutes: 20,
    servings: "1회분",
    tips: "버섯은 처음 도입 시 소량으로 시작해요.",
    tags: ["소고기", "버섯", "진밥"],
  },
  {
    id: "tofu-clear-soup",
    name: "두부 맑은국",
    stage: "후기",
    ageMonths: [10, 12],
    category: "국/찌개",
    summary: "간을 하지 않은 순한 두부 채소국.",
    ingredients: [
      { name: "두부", amount: "30g" },
      { name: "애호박", amount: "15g" },
      { name: "다시물(멸치·다시마)", amount: "180ml" },
    ],
    allergens: ["대두"],
    steps: [
      "다시물을 우려 맑게 준비한다.",
      "애호박을 작게 썰어 넣고 익힌다.",
      "두부를 작게 깍둑 썰어 넣고 데운다.",
    ],
    timeMinutes: 15,
    servings: "1~2회분",
    tips: "후기에는 간 없이 재료 본연의 맛으로.",
    tags: ["두부", "맑은국", "무염"],
  },
  {
    id: "egg-veggie-rice",
    name: "달걀 채소 진밥",
    stage: "후기",
    ageMonths: [10, 12],
    category: "밥/진밥",
    summary: "달걀과 채소를 섞어 부드럽게 익힌 진밥.",
    ingredients: [
      { name: "진밥", amount: "70g" },
      { name: "달걀", amount: "1개" },
      { name: "당근·애호박", amount: "각 10g" },
      { name: "물", amount: "60ml" },
    ],
    allergens: ["계란"],
    steps: [
      "채소를 곱게 다진다.",
      "진밥과 물, 채소를 넣어 끓인다.",
      "달걀을 풀어 넣고 완전히 익을 때까지 저어준다.",
    ],
    timeMinutes: 15,
    servings: "1회분",
    tips: "달걀은 반숙 없이 완전히 익혀 주세요.",
    tags: ["달걀", "채소", "진밥"],
  },
  {
    id: "potato-veggie-pancake",
    name: "감자 채소전",
    stage: "후기",
    ageMonths: [10, 12],
    category: "핑거푸드",
    summary: "손으로 집어 먹기 좋은 부드러운 감자전.",
    ingredients: [
      { name: "감자", amount: "60g" },
      { name: "당근·애호박", amount: "각 10g" },
      { name: "쌀가루", amount: "1큰술" },
    ],
    allergens: [],
    steps: [
      "감자를 갈아 물기를 살짝 뺀다.",
      "곱게 다진 채소와 쌀가루를 섞는다.",
      "약불 팬에 한입 크기로 노릇하게 부친다.",
    ],
    timeMinutes: 20,
    servings: "6~8개",
    tips: "기름은 키친타월로 얇게 펴 바르세요.",
    tags: ["감자", "핑거푸드", "채소"],
  },

  // 완료기 (만 12~15개월)
  {
    id: "beef-veggie-jinbap",
    name: "소고기 채소 진밥",
    stage: "완료기",
    ageMonths: [12, 15],
    category: "밥/진밥",
    summary: "여러 채소와 소고기를 넣은 든든한 진밥.",
    ingredients: [
      { name: "진밥", amount: "90g" },
      { name: "소고기 다짐", amount: "25g" },
      { name: "당근·애호박·양파", amount: "각 10g" },
      { name: "물", amount: "60ml" },
    ],
    allergens: ["쇠고기"],
    steps: [
      "채소를 잘게 다진다.",
      "소고기를 볶다가 채소를 넣어 익힌다.",
      "진밥과 물을 넣어 부드럽게 끓인다.",
    ],
    timeMinutes: 20,
    servings: "1~2회분",
    tips: "간은 하지 않고 재료의 맛으로 충분해요.",
    tags: ["소고기", "채소", "진밥"],
  },
  {
    id: "egg-roll",
    name: "채소 달걀말이",
    stage: "완료기",
    ageMonths: [12, 15],
    category: "반찬",
    summary: "잘게 썬 채소를 넣어 돌돌 만 달걀말이.",
    ingredients: [
      { name: "달걀", amount: "1개" },
      { name: "당근·애호박", amount: "각 10g" },
      { name: "물", amount: "1큰술" },
    ],
    allergens: ["계란"],
    steps: [
      "채소를 아주 곱게 다진다.",
      "달걀을 풀어 물·채소를 섞는다.",
      "약불 팬에 얇게 부쳐 돌돌 말아 한입 크기로 썬다.",
    ],
    timeMinutes: 15,
    servings: "1~2회분",
    tips: "약불에서 천천히 익혀야 부드러워요.",
    tags: ["달걀", "달걀말이", "반찬"],
  },
  {
    id: "radish-beef-soup",
    name: "소고기 뭇국",
    stage: "완료기",
    ageMonths: [12, 15],
    category: "국/찌개",
    summary: "무와 소고기로 끓인 시원하고 순한 국.",
    ingredients: [
      { name: "소고기 다짐", amount: "20g" },
      { name: "무", amount: "30g" },
      { name: "물", amount: "200ml" },
      { name: "국간장", amount: "아주 약간" },
    ],
    allergens: ["쇠고기", "대두", "밀"],
    steps: [
      "무를 작게 깍둑 썬다.",
      "소고기를 볶다가 무를 넣어 함께 볶는다.",
      "물을 붓고 무가 익을 때까지 끓인 뒤 국간장으로 아주 약하게 간한다.",
    ],
    timeMinutes: 25,
    servings: "2회분",
    tips: "국간장은 1/4작은술 이하로, 거의 무염에 가깝게.",
    tags: ["소고기", "무", "국"],
  },

  // 유아 1세 (만 12~24개월)
  {
    id: "cheese-rice-ball",
    name: "치즈 주먹밥",
    stage: "유아 1세",
    ageMonths: [12, 24],
    category: "밥/진밥",
    summary: "아기치즈를 넣어 고소한 한입 주먹밥.",
    ingredients: [
      { name: "밥", amount: "90g" },
      { name: "아기치즈", amount: "1/2장" },
      { name: "당근·시금치", amount: "각 10g" },
      { name: "구운 김가루", amount: "약간" },
    ],
    allergens: ["우유"],
    steps: [
      "채소를 잘게 다져 살짝 볶는다.",
      "따뜻한 밥에 잘게 자른 치즈와 채소를 섞는다.",
      "한입 크기로 동그랗게 뭉치고 김가루를 묻힌다.",
    ],
    timeMinutes: 15,
    servings: "6~8개",
    tips: "치즈는 저염 아기 전용을 사용하세요.",
    tags: ["치즈", "주먹밥", "자기주도"],
  },
  {
    id: "fruit-yogurt",
    name: "과일 요거트",
    stage: "유아 1세",
    ageMonths: [12, 24],
    category: "간식",
    summary: "플레인 요거트에 과일을 더한 간식.",
    ingredients: [
      { name: "플레인 요거트(무가당)", amount: "80g" },
      { name: "바나나·딸기 등", amount: "30g" },
    ],
    allergens: ["우유"],
    steps: [
      "과일을 작게 썰거나 으깬다.",
      "무가당 플레인 요거트에 과일을 섞는다.",
    ],
    timeMinutes: 5,
    servings: "1회분",
    tips: "가당 요거트는 당이 높으니 무가당을 골라요.",
    tags: ["요거트", "과일", "간식"],
  },

  // 유아 2~3세 (만 24~48개월)
  {
    id: "veggie-fried-rice",
    name: "채소 볶음밥",
    stage: "유아 2~3세",
    ageMonths: [24, 48],
    category: "밥/진밥",
    summary: "다진 채소를 듬뿍 넣어 고슬하게 볶은 밥.",
    ingredients: [
      { name: "밥", amount: "120g" },
      { name: "당근·애호박·양파", amount: "각 15g" },
      { name: "달걀", amount: "1개" },
      { name: "참기름", amount: "약간" },
    ],
    allergens: ["계란"],
    steps: [
      "채소를 잘게 다진다.",
      "달걀을 먼저 볶아 덜어둔다.",
      "채소를 볶다가 밥을 넣고 달걀을 섞어 고슬하게 볶는다.",
    ],
    timeMinutes: 15,
    servings: "1~2회분",
    tips: "기호에 따라 잘게 다진 소고기를 더해도 좋아요.",
    tags: ["볶음밥", "채소", "달걀"],
  },
  {
    id: "soft-tofu-soup",
    name: "순두부 채소국",
    stage: "유아 2~3세",
    ageMonths: [24, 48],
    category: "국/찌개",
    summary: "부드러운 순두부를 넣은 순한 국.",
    ingredients: [
      { name: "순두부", amount: "70g" },
      { name: "애호박·양파", amount: "각 15g" },
      { name: "다시물", amount: "200ml" },
      { name: "국간장", amount: "아주 약간" },
    ],
    allergens: ["대두", "밀"],
    steps: [
      "다시물에 채소를 넣어 익힌다.",
      "순두부를 한입 크기로 떠 넣는다.",
      "국간장으로 아주 약하게 간한다.",
    ],
    timeMinutes: 15,
    servings: "2회분",
    tips: "맵지 않게, 고춧가루 없이 맑게 끓여요.",
    tags: ["순두부", "국", "순한맛"],
  },

  // 유아 4~5세 (만 48~72개월)
  {
    id: "chicken-veggie-gratin",
    name: "닭고기 채소 그라탱",
    stage: "유아 4~5세",
    ageMonths: [48, 72],
    category: "반찬",
    summary: "치즈를 올려 부드럽게 구운 한 그릇 반찬.",
    ingredients: [
      { name: "닭안심", amount: "40g" },
      { name: "감자·브로콜리·당근", amount: "각 20g" },
      { name: "우유", amount: "100ml" },
      { name: "아기치즈·밀가루", amount: "각 1큰술" },
    ],
    allergens: ["우유", "밀", "닭고기"],
    steps: [
      "닭고기와 채소를 작게 썰어 익힌다.",
      "밀가루를 우유에 풀어 약불에서 걸쭉한 소스를 만든다.",
      "재료를 그릇에 담고 소스·치즈를 올려 오븐/에어프라이어에 굽는다.",
    ],
    timeMinutes: 30,
    servings: "2회분",
    tips: "소스는 약불에서 저어가며 멍울 없이 만들어요.",
    tags: ["그라탱", "치즈", "한그릇"],
  },
  {
    id: "mild-bibim-noodle",
    name: "순한 비빔국수",
    stage: "유아 4~5세",
    ageMonths: [48, 72],
    category: "밥/진밥",
    summary: "맵지 않게 간장 양념으로 비빈 소면.",
    ingredients: [
      { name: "소면", amount: "60g" },
      { name: "오이·당근·달걀지단", amount: "각 15g" },
      { name: "간장·참기름·통깨", amount: "약간" },
    ],
    allergens: ["밀", "대두", "계란"],
    steps: [
      "소면을 삶아 찬물에 헹군 뒤 짧게 자른다.",
      "오이·당근은 가늘게 채 썰고 달걀지단을 부쳐 썬다.",
      "간장·참기름을 아주 약하게 둘러 비비고 통깨를 뿌린다.",
    ],
    timeMinutes: 20,
    servings: "1~2회분",
    tips: "면은 아이가 먹기 좋게 가위로 짧게 잘라요.",
    tags: ["국수", "비빔", "순한맛"],
  },
];

/** id로 레시피 찾기 */
export function getRecipe(id: string): Recipe | undefined {
  return RECIPES.find((r) => r.id === id);
}
